language: go
go:
  - "1.12"
services:
  - docker
compiler:
  - gcc
env:
  global:
    - TF_VERSION=linux-x86_64-1.12.0 LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
    - GO111MODULE=on

install:
  # tesseract
  - bash setup/scripts/tesseract_install.sh
  # tensorflow
  - bash setup/scripts/tensorflow_install.sh
  # golang dependencies - run separately, to make sure we get the right tags
  # see https://github.com/gen2brain/go-fitz#build-tags
  - go get -u -v -tags nopie github.com/gen2brain/go-fitz

before_script:
  - go vet -tags nopie ./...
  - go build -tags nopie ./...
  - go test -tags nopie -run xxxx ./...
  - make testenv

script:
  - go fmt ./...
  - go run golang.org/x/lint/golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
  - go test -tags nopie -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build