language: go
go:
  - "1.11"
services:
  - docker
sudo: required

install:
  - go get -u golang.org/x/lint/golint
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - sh ./setup/scripts/tensorflow_install.sh
  - dep ensure

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...
  - make testenv
  
script:
  - go fmt ./...
  - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
  - go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
