language: go
go:
  - "1.11"
services:
  - docker
env:
  - TF_VERSION=linux-x86_64-1.12.0
compiler:
  - g++
env:
  - TF_VERSION=linux-x86_64-1.12.0 LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

install:
  # tesseract
  - bash setup/scripts/tesseract_install.sh
  # tensorflow
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - curl -L "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-${TF_VERSION}.tar.gz" | sudo tar -C /usr/local -xz
  - sudo ldconfig
  # golang dependencies
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/gen2brain/go-fitz
  - dep ensure -v

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...
  - make testenv

script:
  - go fmt ./...
  - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
  - go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
