language: go
go:
  - "1.11"
services:
  - docker
compiler:
  - gcc
env:
  - TF_VERSION=linux-x86_64-1.12.0 LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

install:
  # tesseract
  - bash setup/scripts/tesseract_install.sh
  # tensorflow
  - bash setup/scripts/tensorflow_install.sh
  # golang dependencies
  - go get -u golang.org/x/lint/golint
  - go get -u -v -tags nopie github.com/gen2brain/go-fitz # https://github.com/gen2brain/go-fitz#build-tags
  - GO111MODULE=on go mod download

before_script:
  - go vet -tags nopie ./...
  - go build -tags nopie ./...
  - go test -tags nopie -run xxxx ./...
  - make testenv

script:
  - go fmt ./...
  - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
  #- go test -tags nopie -race -short -coverprofile=coverage.txt ./...
  - go test -tags nopie -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
