[[constraint]]
  name = "github.com/tensorflow/tensorflow"
  branch = "r1.12"

[[constraint]]
  name = "github.com/RTradeLtd/grpc"
  version = "v1.0.6-rc4" 

[[constraint]]
  name = "github.com/DavidBelicza/TextRank"
  version = "2.1.1"

[[constraint]]
  name = "github.com/RTradeLtd/cmd"
  version = "1.0.4-rc1"

[[constraint]]
  name = "github.com/RTradeLtd/config"
  version = "v1.0.8-rc2"

[[constraint]]
  name = "github.com/RTradeLtd/database"
  version = "1.0.4"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.1.1"

[[constraint]]
  name = "github.com/ipfs/go-cid"
  version = "0.9.0"

[prune]
  go-tests = true
  unused-packages = true
