
[prune]
  go-tests = true
  unused-packages = true

###############
#   RTRADE    #
###############

[[constraint]]
  name = "github.com/RTradeLtd/grpc"
  version = "v1.0.5b"

[[constraint]]
  name = "github.com/RTradeLtd/rtfs"
  version = "v0.3.0"

[[constraint]]
  name = "github.com/RTradeLtd/cmd"
  version = "v1.0.4"

[[constraint]]
  name = "github.com/RTradeLtd/config"
  version = "v1.0.11"

###############
# THIRD PARTY #
###############

[[constraint]]
  name = "github.com/tensorflow/tensorflow"
  branch = "r1.12"

[[constraint]]
  name = "github.com/DavidBelicza/TextRank"
  version = "2.1.1"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.1.1"

[[constraint]]
  name = "github.com/ipfs/go-cid"
  version = "0.9.0"

[[constraint]]
  name = "github.com/otiai10/gosseract"
  version = "2.2.0"
